In [7]:
# Theories
import numpy as np
import torch
import tensorflow as tf


arr_2d_zeros = np.zeros((2, 3))
pt_2d_zeros = torch.zeros((2, 3))
tf_2d_zeros = torch.zeros((2, 3))

print(arr_2d_zeros)
print(pt_2d_zeros)
print(tf_2d_zeros)

[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
arr_2d_ones = np.ones((2, 3))
pt_2d_ones = torch.ones((2, 3))
tf_2d_ones = tf.ones((2, 3))

print(arr_2d_ones)
print(pt_2d_ones)
print(tf_2d_ones)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [16]:
# Full or fill

arr_2d_nines = np.full((2, 3), 9)
pt_2d_nines = torch.full((2, 3), 9)
tf_2d_nines = tf.fill((2, 3), 9)

print(arr_2d_nines)
print(pt_2d_nines)
print(tf_2d_nines)

[[9 9 9]
 [9 9 9]]
tensor([[9, 9, 9],
        [9, 9, 9]])
tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [1]:
# Question 1: Implement a function to create a matrix of 3x4 filled with 0 by
# using Numpy, Tensorflow and Pytorch

import numpy as np
import tensorflow as tf
import torch

def create_matrix_zeros(size=(3,4), lib='np'):
    '''
    Return a matrix with the size as `size` and datatype as `lib` 
    
    Args:
        size (tuple): size of the matrix
        lib (str): type of the matrix. lib can be either of 'np', 'pt', 'tf'
    '''
    matrix =  None
    
    if lib == 'np':
        matrix = np.zeros(size)
    elif lib == 'pt':
        matrix = torch.zeros(size)
    elif lib == 'tf':
        matrix = tf.zeros(size)
    else:
        print('Invalid data type')

    return matrix


print(create_matrix_zeros())
print(create_matrix_zeros((3, 4), 'tf'))
print(create_matrix_zeros((3, 4), 'pt'))



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [2]:
# Question 2: Implement a function to create a matrix of 3x4 filled with 1 by
# using Numpy, Tensorflow and Pytorch

def create_matrix_ones(size=(3,4), lib='np'):
    '''
    Return a matrix with the size as `size` and datatype as `lib` 
    
    Args:
        size (tuple): size of the matrix
        lib (str): type of the matrix. lib can be either of 'np', 'pt', 'tf'
    '''
    matrix =  None
    
    if lib == 'np':
        matrix = np.ones(size)
    elif lib == 'pt':
        matrix = torch.ones(size)
    elif lib == 'tf':
        matrix = tf.ones(size)
    else:
        print('Invalid data type')

    return matrix


print(create_matrix_ones())
print(create_matrix_ones((3, 4), 'tf'))
print(create_matrix_ones((3, 4), 'pt'))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
# Question 3: Implement a function to create a matrix of any size (e.g 3x4) filled with any number (e.g 7) by
# using Numpy, Tensorflow and Pytorch

def create_matrix_with_value(size=(3,4), value=5, lib='np'):
    '''
    Return a matrix with the size as `size` and datatype as `lib` and fill
    with value
    
    Args:
        size (tuple): size of the matrix
        lib (str): type of the matrix. lib can be either of 'np', 'pt', 'tf'
        value (float or int): value to be filled with
    '''

    matrix =  None
    
    if lib == 'np':
        matrix = np.full(size, value)
    elif lib == 'pt':
        matrix = torch.full(size, value)
    elif lib == 'tf':
        matrix = tf.fill(size, value)
    else:
        return 'Invalid data type'

    return matrix


print(create_matrix_with_value())
print(create_matrix_with_value((4, 9), 20, 'pt'))
print(create_matrix_with_value((4, 9), 20, 'tf'))



[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
tensor([[20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20],
        [20, 20, 20, 20, 20, 20, 20, 20, 20]])
tf.Tensor(
[[20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20]
 [20 20 20 20 20 20 20 20 20]], shape=(4, 9), dtype=int32)
