In [18]:
import numpy as np

def padding(matrix):
    '''Padding of matrix'''

    # Get image shape
    rows, cols = matrix.shape
    
    # Generate the padded matrix
    padded_rows, padded_cols = rows + 2, cols + 2
    padded_img = np.zeros((padded_rows, padded_cols))
    
    # Loop through the input matrix and fill in the padded_img
    for i in range(rows):
        for j in range(cols):
            value = matrix[i, j]



            # Position of value in the padded_img
            x, y = i + 1, j + 1

            # Update value to the padded_img
            padded_img[x, y] = value

    return padded_img



input_matrix = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
])

print(padding(input_matrix))

[[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]
